### ISSUE TITLE
Copper block and oxidised copper block remain as vanilla texture with Create: legacy copper resource pack enabled when Xycraft: installed

### ISSUE THREAD

**Issue by Branjoman** [Soaryn/XyCraftTracker#17]
**Describe the bug**
When both the Xycraft: Override metal overrides and Create: Legacy Copper resource packs are enabled, the copper block and oxidized copper block use their vanilla texture instead of the create legacy texture.

**To Reproduce**
 - Install Create v0.5.0i
 - Turn on the Create Legacy Copper resource pack
 - Copper block and oxidized copper block textures have now not changed over as they should have
**Expected behavior**
All oxidation states of the copper block should have the create legacy texture.

**Screenshots**
https://i.imgur.com/2TM6Vjg.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - XyCraft Core Version: 0.5.17

**Additional context**
Duplicate of the issue on the Create github for reference: https://github.com/Creators-of-Create/Create/issues/4523

**Comment by Soaryn** [comment]
Curiously, what is the order of the resource packs in the list?

**Comment by Branjoman** [comment]
In the initial report the create legacy copper pack was below all the xycraft packs, moving it above them or in between them in any order doesn't seem to have any effect on the issue.

**Comment by Soaryn** [comment]
Which ever one you desire needs to be on the top of the list, though past that, that is just using Vanilla's system

Curiously, try (assuming you want the create one) pushing the xy one all the way to the bottom (below minecraft's)

**Comment by Soaryn** [comment]
Finally had time to sit down and hash out the issue. This is caused primarily because of how Override has the resource packs defined. This however causes some issues: The intent is to have resource packs that are turned on by default, but with the option to turn them off. The option to turn them off is not simple to add in since Forge doesn't quite handle that scenario, so the temp solution was to just order the resource packs. In order to turn one off, you need to move it below the `Minecraft` default resource pack ultimately wiping any changes made by my resources. 

The Create resource pack changes the texture, and only the texture.
The XyCraft resource pack changes the texture and the model. 

Because of the model change, the wrong model gets loaded thus indicating the wrong texture gets used. 

I'll talk to Simi to see if we can devise a solution that makes them collaborate better together.

**Comment by Soaryn** [comment]
Should be fixed in a future version of Create.
