### ISSUE TITLE
[Bug]: Collector accessing invalid blockstate on neighbor block

### ISSUE THREAD

**Issue by JaisDK** [Soaryn/XyCraftTracker#48]
### Mod Title

XyCraft Machines

### Minecraft Version

1.21.0

### Severity

Crashing

### NeoForge Version

21.0.51-beta

### Describe the Suggestion

stop crashing

### Reproduction Steps

log provided

### Additional Context

https://mclo.gs/edGHu4J

**Comment by Soaryn** [comment]
Did you perchance move a collector with something that doesnt break the block, like a wand of moving or something. Just trying to figure out how it got there 🤔

**Comment by Soaryn** [comment]
I seemingly can't replicate this, so I feel like something moved the collector without calling `onRemove` for the block.

**Comment by JaisDK** [comment]
it was a report from ATM discord, not my own game
maybe you can just put a check for that blockstate before querying it since this situation can happen

**Comment by Soaryn** [comment]
The problem is, that shouldnt happen, adding a check just hides the problem, not so much solves anything, and infact results in even stranger behaviour as well as a performance degradation 😂

This is either something went terribly wrong, which I cant replicate, or some mod allows you to swap blocks and doesnt call on remove, which would affect a fair amount of mods. I kind of need who ever mentioned this in the discord to try their best to remember how they mutated the blocks around (including the collector)

**Comment by Soaryn** [comment]
I have been looking at various options in ATM10 that could cause this, and I so far can't find anything from pure guessing. I looked into it, and just merely checking the state would cause a rather significant amount of grief on both my side and any things like pipes hooked up to the collector.

**Comment by Soaryn** [comment]
Ok, Last attempts, assuming you know who reported it, can you ask if they were using spatial storage from AE?

**Comment by Soaryn** [comment]
Added something to `v0.7.28` that should at least alleviate the crashes as well as prevent moving the blocks with Spatial Storage. As specifically that one was the only one I could replicate it with.

**Comment by Soaryn** [comment]
`v0.7.28` has been released, Understandably this bug wasn't yours, but this should actually fix that world as well if you are able to inform the original person who had it. Do let me know if they are still causing grief
