### ISSUE TITLE
[Suggestion]: Limit Ore Geyser spawning to mountain biomes

### ISSUE THREAD

**Issue by Kevin-Marsh** [Soaryn/XyCraftTracker#49]
### XyCraft Module

Machines

### Describe the Suggestion

Ore geysers spawn a bit randomly and seem out of place in the middle of a grassy plain. I suggest limiting the spawn to replace stone in a mountain biome.

**Comment by Soaryn** [comment]
It is intended to be in most parts of the world as it's our main source of infrastructure planned, but there is a tag to be able to indicate which biomes are valid (and in theory, I'll have to check, invalid) . The appearance is something I want to work on still.

**Comment by Soaryn** [comment]
In `0.7.32+` (unreleased as we are getting ready for ForgeCraft) the nodes are more spaced out (by about 15 chunks rather than 7 in current), but the intent of the ore geysers are to provide Satisfactory like Ore Nodes around the world that server as Points of Interest for a player. While I can see the desire for mountains only, and it was actually considered, the problems associated with it are usually reliant on RNG to make said mountains. I WILL however look into making something along the lines of some configurations to be able to use for the data set. but that is at the moment sadly low on the priority chain. I've made note though to look back over generation in future versions.
