### ISSUE TITLE
[Question] Where is the asset for the animated shimmer on xychorium storage blocks? 

### ISSUE THREAD

**Issue by Manos-of-Fate** [Soaryn/XyCraftTracker#65]
I'm working on a modpack that will include full HD texture support and having the base texture file helps a ton for reference, especially with animated textures. I've looked everywhere and can't find it.

**Comment by Soaryn** [comment]
Uhhhhh there isn't a file 😅 Maaagic! 😊

**Comment by Manos-of-Fate** [comment]
Damn. Those blocks would go so well with my pack, but it's basically impossible to use an animated and interpolated texture as a reference in game. :(

**Comment by Soaryn** [comment]
Sorry, if the goal of this is to make a new texture based on it, that will be quite a challenge. I've tried many times, but because it is an evolving texture, it can't really be made into a 1:1 framed icon, nor should we given how many frames would be resultant.

If you wanted to just have it show up in other blocks/models, that is far simpler given it is still on the block atlas.
